[package]
name = "pillow-rs-js"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "wasm-bindgen bindings for pillow-rs — Pillow in the browser"

[lib]
crate-type = ["cdylib"]

[dependencies]
pillow-rs = { path = "../pillow-rs" }
log = "0.4"
wasm-bindgen = "0.2"
js-sys = "0.3"
console_error_panic_hook = "0.1"
console_log = "1.0"

[profile.release]
lto = true
opt-level = "s"
