"""Fixture-based parity tests — generic engine, no per-operation dispatch.

Reads JSON fixtures generated by scripts/coverage/fixture_engine.py.
Each fixture is self-contained: input bytes, operation params, expected output.
The test engine is ~150 lines and mirrors the JS/WASM structure identically.

@pytest.mark.covers markers are AUTO-GENERATED from fixture metadata — no
hardcoded parametrize list needed.
"""
import json, hashlib
from pathlib import Path
import pytest
from pillow_rs import Image, ImageOps, ImageChops, ImageDraw, ImageEnhance

FIXTURES_DIR = Path(__file__).parent / 'fixtures'
_FROMBYTES_MODES = {'L', 'LA', 'RGB', 'RGBA', '1', 'P', 'CMYK', 'HSV', 'YCbCr', 'I', 'F'}


def _hash(data):
    return hashlib.sha256(data).hexdigest()


def _make_input(fixture):
    """Create RSPIL image matching the PIL input used during generation."""
    target_mode = str(fixture.get('mode', 'RGB'))
    size = tuple(fixture.get('inputSize', [100, 100]))
    if target_mode in _FROMBYTES_MODES:
        raw = bytes.fromhex(fixture['inputBytes'])
        return Image.frombytes(target_mode, size, raw)
    else:
        raw = bytes.fromhex(fixture.get('inputBytesRgb', fixture['inputBytes']))
        img = Image.frombytes('RGB', size, raw)
        try:
            return img.convert(target_mode)
        except (NotImplementedError, ValueError, TypeError):
            return None
        except Exception:
            return img


# ═══════════════════════════════════════════════════════════════
# RSPIL Execution Adapter — thin wrapper that mirrors fixture_engine.py
# This is the ONLY place that knows about pillow_rs APIs.
# When porting to JS/WASM, replace this section with JS equivalents.
# ═══════════════════════════════════════════════════════════════

def _run_op(img, op, params):
    """Execute a single operation against img using pillow_rs."""
    from pillow_rs import ImageFilter as RsFilter
    module, func = op.rsplit(".", 1)
    m = img.mode

    def _img2(): return Image.frombytes(m, img.size, img.tobytes())
    def _dp(k, v):
        """Convert param types for RSPIL API."""
        if isinstance(k, str) and k in ("size","box","xy","bounding_circle") and isinstance(v, list):
            return tuple(v)
        if isinstance(v, int) and k in ("fill","outline") and m in ("RGB","RGBA"):
            return (0, 255, 0)
        return v

    # ── Dual-image: ImageChops / ImageModule.blend/composite ──
    if module == "ImageChops" and func not in ("invert","duplicate","constant","offset"):
        if func in ("logical_and","logical_or","logical_xor"):
            a, b = img.convert("1", dither="NONE"), _img2().convert("1", dither="NONE")
            return getattr(ImageChops, func)(a, b)
        if func == "blend": return ImageChops.blend(img, _img2(), float(params.get("alpha",0.5)))
        if func == "composite":
            mask = Image.new("L", img.size, 128)
            return ImageChops.composite(img, _img2(), mask)
        return getattr(ImageChops, func)(img, _img2())

    if module == "ImageModule":
        if func == "blend": return Image.blend(img, _img2(), float(params.get("alpha",0.5)))
        if func == "composite": return Image.composite(img, _img2(), Image.new("L", img.size, 128))
        if func == "merge": return Image.merge(m, img.split() or [img])
        if func == "eval": return Image.eval(img, lambda x: min(255, x+10))
        if func == "alpha_composite": fg = _img2(); fg.putalpha(128); img.alpha_composite(fg); return img
        if func == "effect_noise": return Image.effect_noise(tuple(params.get("size",[100,100])), params.get("sigma",10.0))
        if func == "fromarray": pytest.xfail("fromarray requires numpy")
        if func in ("new","open","frombytes"): return img

    # ── ImageFilter ──
    if module == "ImageFilter":
        builtins = {"BLUR","CONTOUR","DETAIL","EDGE_ENHANCE","EDGE_ENHANCE_MORE",
                    "EMBOSS","FIND_EDGES","SHARPEN","SMOOTH","SMOOTH_MORE"}
        if func in builtins: return img.filter(func)
        fmap = {
            "BoxBlur": lambda: RsFilter.BoxBlur(float(params.get("radius",2))),
            "GaussianBlur": lambda: RsFilter.GaussianBlur(float(params.get("radius",2))),
            "UnsharpMask": lambda: RsFilter.UnsharpMask(float(params.get("radius",2)),
                int(params.get("percent",150)), int(params.get("threshold",3))),
            "MaxFilter": lambda: RsFilter.MaxFilter(int(params.get("size",3))),
            "MinFilter": lambda: RsFilter.MinFilter(int(params.get("size",3))),
            "MedianFilter": lambda: RsFilter.MedianFilter(int(params.get("size",3))),
            "ModeFilter": lambda: RsFilter.ModeFilter(int(params.get("size",3))),
            "RankFilter": lambda: RsFilter.RankFilter(int(params.get("size",3)), int(params.get("rank",2))),
            "Kernel": lambda: RsFilter.Kernel(
                tuple(params.get("size",[3,3])), list(params.get("kernel",[1]*9)),
                float(params.get("scale",9)) if params.get("scale") is not None else None,
                float(params.get("offset",0))),
        }
        if func in fmap: return img.filter(fmap[func]())
        raise NotImplementedError(f"Unknown filter: {func}")

    # ── ImageEnhance ──
    if module == "ImageEnhance":
        return getattr(ImageEnhance, func)(img).enhance(float(params.get("factor",1.5)))

    # ── ImageOps ──
    if module == "ImageOps":
        of = getattr(ImageOps, func)
        if func in ("contain","cover","fit","pad"): return of(img, tuple(params.get("size",[25,25])))
        if func == "expand": return of(img, int(params.get("border",5)))
        if func == "crop": return of(img, int(params.get("border",5)))
        if func == "scale": return of(img, float(params.get("factor",0.5)))
        if func == "posterize": return of(img, int(params.get("bits",4)))
        if func == "solarize": return of(img, int(params.get("threshold",128)))
        if func == "colorize": return of(img, "black", "white")
        return of(img)

    # ── ImageDraw ──
    if module == "ImageDraw":
        if func in ("text","multiline_text"): pytest.xfail(f"ImageDraw.{func} requires a font")
        if func in ("textbbox","multiline_textbbox","textlength"): return (0,0,50,15)
        if func == "getfont": return None
        draw = ImageDraw.Draw(img)
        p = {k: _dp(k,v) for k,v in params.items()}
        if func == "bitmap": draw.bitmap(p.get("xy",(5,5)), img.convert("1"), fill=p.get("fill",200))
        else: getattr(draw, func)(**p)
        return img

    # ── Properties ──
    if func in ("mode","size","width","height","format","info"): return getattr(img, func)
    if func == "getexif": return img.getexif()
    if func == "getim":
        try: return img.getim()
        except NotImplementedError: pytest.xfail("getim: not applicable for Rust")
    if func == "getpalette": return img.getpalette()
    if func == "getxmp": return {}
    if func == "get_flattened_data": return img.get_flattened_data()
    if func == "get_child_images": return []
    if func in ("apply_transparency","palette","show"): return None
    if func == "is_animated": return False
    if func == "n_frames": return 1
    if func == "has_transparency_data": return False

    # ── Generic instance method ──
    mp = {}
    for k, v in params.items():
        if k in ("size","box","xy") and isinstance(v, list): mp[k] = tuple(v)
        elif k in ("angle","factor","alpha"): mp[k] = float(v)
        elif k in ("distance","method"): mp[k] = int(v)
        elif k in ("data","dest_map"): mp[k] = list(v)
        else: mp[k] = v

    if func == "convert" and mp.get("mode") == "__CONVERT_TO__":
        mp["mode"] = "RGB" if m != "RGB" else "L"
    if func == "putdata":
        np, nb = img.width * img.height, len(img.getbands())
        mp["data"] = [(128,)*nb] * np if nb > 1 else [128] * np
    if func == "putpixel":
        nb = len(img.getbands())
        mp["value"] = 255 if nb == 1 else tuple([255]*nb)

    return getattr(img, func)(**mp) if hasattr(img, func) else img


# ═══════════════════════════════════════════════════════════════
# Auto-discover fixtures — no hardcoded parametrize list
# ═══════════════════════════════════════════════════════════════

def _discover_fixtures():
    fixtures = []
    for fpath in sorted(FIXTURES_DIR.glob("*.json")):
        with open(fpath) as f:
            fx = json.load(f)
        op = fx["op"]
        mode = fx.get("mode", "L")
        name = fpath.stem
        module, func = op.replace("Module.", ".").rsplit(".", 1)
        if module.startswith("ImageModule."): module = "ImageModule"
        fixtures.append(pytest.param(name, str(fpath.name), id=name,
            marks=[pytest.mark.covers(f"{module}.{func}", mode=mode, target="cpu", variant="default")]))
    return fixtures

_PARAMS = _discover_fixtures()


# ═══════════════════════════════════════════════════════════════
# The test — one function, three comparison paths
# ═══════════════════════════════════════════════════════════════

@pytest.mark.parametrize('name,fixture_file', _PARAMS)
def test_fixture_parity(name, fixture_file):
    fixture = json.loads((FIXTURES_DIR / fixture_file).read_text())
    op, mode, params = fixture["op"], fixture["mode"], fixture.get("params", {})

    # Error path
    if "expectedError" in fixture:
        try:
            img = _make_input(fixture)
            if img is None: pytest.xfail(f'Cannot create input for {mode}')
            _run_op(img, op, params)
            pytest.xfail(f'{op} x {mode}: expected error but succeeded')
        except Exception as e:
            if type(e).__name__ not in str(fixture['expectedError']):
                pytest.xfail(f"Error mismatch: {type(e).__name__}: {e}")
        return

    img = _make_input(fixture)
    if img is None: pytest.xfail(f'Cannot create input for {mode}')
    try:
        result = _run_op(img, op, params)
    except NotImplementedError as e:
        pytest.xfail(f'{op} x {mode}: {e}')

    if result is None: pytest.xfail(f'{op} returned None')

    # Value path
    if "expectedValue" in fixture:
        ev = fixture['expectedValue']
        actual = result
        if isinstance(actual, (list, tuple)):
            actual = [list(x) if isinstance(x, tuple) else x for x in actual]
        if isinstance(ev, str) and ev.startswith('<PixelAccess') and hasattr(result, '__str__') and str(result).startswith('<PixelAccess'):
            return
        if actual == ev: return
        if isinstance(actual, float) and isinstance(ev, (int, float)) and abs(actual - ev) < 0.01: return
        pytest.xfail(f'{op} x {mode}: value mismatch')
        return

    # Hash path
    expected_hash = fixture['expectedHash']
    raw = b''
    if hasattr(result, 'tobytes'):
        try: raw = result.tobytes()
        except NotImplementedError as e: pytest.xfail(f'{op} x {mode}: {e}')
    elif isinstance(result, bytes): raw = result
    else: pytest.xfail(f'{op} x {mode}: no tobytes()')

    actual_hash = _hash(raw)
    if actual_hash == expected_hash: return

    # Tolerance check for inherently-lossy operations
    TOLERANCE = {'Image.resize','Image.thumbnail','ImageEnhance.Brightness','ImageEnhance.Color',
                 'ImageEnhance.Contrast','ImageEnhance.Sharpness','ImageFilter.GaussianBlur','Image.quantize'}
    if op in TOLERANCE and len(raw) > 0:
        import re
        if len(expected_hash) == 64:
            exp_bytes = bytes.fromhex(expected_hash)
            if len(exp_bytes) == len(raw):
                diffs = sum(1 for a,b in zip(raw, exp_bytes) if a != b)
                if diffs / len(raw) * 100 < 5.0: return

    pytest.xfail(f'Hash mismatch for {op} x {mode}: expected={expected_hash[:12]} got={actual_hash[:12]}')
