//! Minimal OpenType CFF/Type2 outline loading.
//!
//! This covers the simple, non-CID CFF table shape generated by the compact
//! public parity fixtures: Top DICT `CharStrings` plus direct Type2 path
//! operators without subroutines.

use crate::error::FontError;
use crate::tt::glyf::{GlyphOutline, OutlinePoint};

const TYPE2_TAG_ON: u8 = 0x01;
const TYPE2_TAG_CUBIC: u8 = 0x02;

#[derive(Debug, Clone)]
pub struct CffTable {
    charstrings: Vec<Vec<u8>>,
}

pub fn parse_cff(data: &[u8]) -> Result<CffTable, FontError> {
    if data.len() < 4 {
        return Err(FontError::InvalidFont("CFF: header too short".into()));
    }
    let header_size = usize::from(data[2]);
    let mut pos = header_size;
    let (_, next) = read_index(data, pos)?;
    pos = next;
    let (top_dict_index, next) = read_index(data, pos)?;
    pos = next;
    let top_dict = top_dict_index
        .first()
        .ok_or_else(|| FontError::InvalidFont("CFF: missing Top DICT".into()))?;
    let (_, next) = read_index(data, pos)?;
    pos = next;
    let (_, _) = read_index(data, pos)?;

    let top = parse_top_dict(top_dict)?;
    let charstrings_offset = top
        .charstrings_offset
        .ok_or_else(|| FontError::InvalidFont("CFF: missing CharStrings offset".into()))?;
    let (charstrings, _) = read_index(data, charstrings_offset)?;
    Ok(CffTable {
        charstrings: charstrings.into_iter().map(<[u8]>::to_vec).collect(),
    })
}

impl CffTable {
    pub fn load_glyph(&self, glyph_index: u16) -> Result<GlyphOutline, FontError> {
        let charstring = self
            .charstrings
            .get(usize::from(glyph_index))
            .ok_or_else(|| FontError::InvalidOutline("CFF: glyph index out of range".into()))?;
        Type2Decoder::new(charstring).decode()
    }
}

#[derive(Default)]
struct TopDict {
    charstrings_offset: Option<usize>,
}

fn parse_top_dict(data: &[u8]) -> Result<TopDict, FontError> {
    let mut pos = 0usize;
    let mut stack = Vec::new();
    let mut dict = TopDict::default();
    while pos < data.len() {
        let byte = data[pos];
        if byte <= 21 {
            pos += 1;
            let op = if byte == 12 {
                let escaped = *data.get(pos).ok_or_else(|| {
                    FontError::InvalidFont("CFF: escaped dict op overflow".into())
                })?;
                pos += 1;
                0x0C00 | u16::from(escaped)
            } else {
                u16::from(byte)
            };
            if op == 17 {
                let offset = stack.last().copied().ok_or_else(|| {
                    FontError::InvalidFont("CFF: CharStrings operand missing".into())
                })?;
                dict.charstrings_offset = usize::try_from(offset).ok();
            }
            stack.clear();
        } else {
            let (number, next) = read_dict_number(data, pos)?;
            stack.push(number);
            pos = next;
        }
    }
    Ok(dict)
}

fn read_index(data: &[u8], pos: usize) -> Result<(Vec<&[u8]>, usize), FontError> {
    let count_bytes = data
        .get(pos..pos + 2)
        .ok_or_else(|| FontError::InvalidFont("CFF: INDEX count overflow".into()))?;
    let count = usize::from(u16::from_be_bytes([count_bytes[0], count_bytes[1]]));
    let mut cursor = pos + 2;
    if count == 0 {
        return Ok((Vec::new(), cursor));
    }
    let off_size = usize::from(
        *data
            .get(cursor)
            .ok_or_else(|| FontError::InvalidFont("CFF: INDEX offSize missing".into()))?,
    );
    cursor += 1;
    if !(1..=4).contains(&off_size) {
        return Err(FontError::InvalidFont("CFF: invalid INDEX offSize".into()));
    }
    let mut offsets = Vec::with_capacity(count + 1);
    for _ in 0..=count {
        let mut value = 0usize;
        for _ in 0..off_size {
            value =
                (value << 8)
                    | usize::from(*data.get(cursor).ok_or_else(|| {
                        FontError::InvalidFont("CFF: INDEX offset overflow".into())
                    })?);
            cursor += 1;
        }
        offsets.push(value);
    }
    let object_base = cursor;
    let mut objects = Vec::with_capacity(count);
    for pair in offsets.windows(2) {
        let start = pair[0]
            .checked_sub(1)
            .ok_or_else(|| FontError::InvalidFont("CFF: INDEX offset underflow".into()))?;
        let end = pair[1]
            .checked_sub(1)
            .ok_or_else(|| FontError::InvalidFont("CFF: INDEX offset underflow".into()))?;
        if end < start {
            return Err(FontError::InvalidFont(
                "CFF: INDEX offsets out of order".into(),
            ));
        }
        objects.push(
            data.get(object_base + start..object_base + end)
                .ok_or_else(|| FontError::InvalidFont("CFF: INDEX object overflow".into()))?,
        );
    }
    let last = offsets
        .last()
        .copied()
        .ok_or_else(|| FontError::InvalidFont("CFF: INDEX offsets missing".into()))?
        .checked_sub(1)
        .ok_or_else(|| FontError::InvalidFont("CFF: INDEX offset underflow".into()))?;
    Ok((objects, object_base + last))
}

fn read_dict_number(data: &[u8], pos: usize) -> Result<(i32, usize), FontError> {
    let byte = *data
        .get(pos)
        .ok_or_else(|| FontError::InvalidFont("CFF: dict number overflow".into()))?;
    match byte {
        28 => {
            let bytes = data
                .get(pos + 1..pos + 3)
                .ok_or_else(|| FontError::InvalidFont("CFF: shortint overflow".into()))?;
            Ok((i32::from(i16::from_be_bytes([bytes[0], bytes[1]])), pos + 3))
        }
        29 => {
            let bytes = data
                .get(pos + 1..pos + 5)
                .ok_or_else(|| FontError::InvalidFont("CFF: longint overflow".into()))?;
            Ok((
                i32::from_be_bytes([bytes[0], bytes[1], bytes[2], bytes[3]]),
                pos + 5,
            ))
        }
        30 => read_real_number(data, pos + 1),
        32..=246 => Ok((i32::from(byte) - 139, pos + 1)),
        247..=250 => {
            let next =
                i32::from(*data.get(pos + 1).ok_or_else(|| {
                    FontError::InvalidFont("CFF: positive number overflow".into())
                })?);
            Ok((((i32::from(byte) - 247) * 256) + next + 108, pos + 2))
        }
        251..=254 => {
            let next =
                i32::from(*data.get(pos + 1).ok_or_else(|| {
                    FontError::InvalidFont("CFF: negative number overflow".into())
                })?);
            Ok((-((i32::from(byte) - 251) * 256) - next - 108, pos + 2))
        }
        _ => Err(FontError::InvalidFont("CFF: invalid DICT number".into())),
    }
}

fn read_real_number(data: &[u8], mut pos: usize) -> Result<(i32, usize), FontError> {
    let mut text = String::new();
    loop {
        let byte = *data
            .get(pos)
            .ok_or_else(|| FontError::InvalidFont("CFF: real number overflow".into()))?;
        pos += 1;
        for nibble in [byte >> 4, byte & 0x0F] {
            match nibble {
                0..=9 => text.push(char::from(b'0' + nibble)),
                0xA => text.push('.'),
                0xB | 0xC => text.push('E'),
                0xE => text.push('-'),
                0xF => {
                    let rounded = text.parse::<f32>().unwrap_or(0.0).round();
                    return Ok((rounded as i32, pos));
                }
                _ => {}
            }
        }
    }
}

struct Type2Decoder<'a> {
    data: &'a [u8],
    pos: usize,
    stack: Vec<i32>,
    x: i32,
    y: i32,
    points: Vec<OutlinePoint>,
    end_pts: Vec<u16>,
    contour_start: Option<usize>,
    width_seen: bool,
}

impl<'a> Type2Decoder<'a> {
    fn new(data: &'a [u8]) -> Self {
        Self {
            data,
            pos: 0,
            stack: Vec::new(),
            x: 0,
            y: 0,
            points: Vec::new(),
            end_pts: Vec::new(),
            contour_start: None,
            width_seen: false,
        }
    }

    fn decode(mut self) -> Result<GlyphOutline, FontError> {
        while self.pos < self.data.len() {
            let byte = self.data[self.pos];
            if byte <= 31 && byte != 28 {
                self.pos += 1;
                match byte {
                    4 => self.vmoveto()?,
                    5 => self.rlineto()?,
                    6 => self.hv_line(true)?,
                    7 => self.hv_line(false)?,
                    8 => self.rrcurveto()?,
                    14 => {
                        self.drop_endchar_width();
                        self.close_contour()?;
                        break;
                    }
                    21 => self.rmoveto()?,
                    22 => self.hmoveto()?,
                    30 => self.vhcurveto()?,
                    31 => self.hvcurveto()?,
                    12 => {
                        return Err(FontError::InvalidOutline(
                            "CFF: escaped Type2 op unsupported".into(),
                        ));
                    }
                    _ => {
                        return Err(FontError::InvalidOutline(format!(
                            "CFF: Type2 op {byte} unsupported"
                        )));
                    }
                }
                self.stack.clear();
            } else {
                let (number, next) = read_type2_number(self.data, self.pos)?;
                self.stack.push(number);
                self.pos = next;
            }
        }
        self.build_outline()
    }

    fn build_outline(self) -> Result<GlyphOutline, FontError> {
        if self.points.is_empty() {
            return Ok(GlyphOutline::default());
        }
        let mut xmin = self.points[0].x;
        let mut ymin = self.points[0].y;
        let mut xmax = self.points[0].x;
        let mut ymax = self.points[0].y;
        for point in &self.points {
            xmin = xmin.min(point.x);
            ymin = ymin.min(point.y);
            xmax = xmax.max(point.x);
            ymax = ymax.max(point.y);
        }
        let num_contours = u16::try_from(self.end_pts.len())
            .map_err(|_| FontError::InvalidOutline("CFF: too many contours".into()))?;
        Ok(GlyphOutline {
            num_contours,
            end_pts_of_contours: self.end_pts,
            points: self.points,
            xmin,
            ymin,
            xmax,
            ymax,
            bbox_xmin: xmin,
            is_composite: false,
            sub_lsb: 0,
            instructions: Vec::new(),
            components: Vec::new(),
            outline_flags: 0,
            has_cubic_tags: true,
        })
    }

    fn take_width_for(&mut self, arg_count: usize) {
        if !self.width_seen && self.stack.len() > arg_count {
            self.stack.remove(0);
        }
        self.width_seen = true;
    }

    fn drop_endchar_width(&mut self) {
        if !self.width_seen && self.stack.len() == 1 {
            self.stack.clear();
        }
        self.width_seen = true;
    }

    fn move_to(&mut self, dx: i32, dy: i32) -> Result<(), FontError> {
        self.close_contour()?;
        self.x += dx;
        self.y += dy;
        self.contour_start = Some(self.points.len());
        self.points.push(OutlinePoint {
            x: self.x,
            y: self.y,
            on_curve: true,
            tag: TYPE2_TAG_ON,
        });
        Ok(())
    }

    fn close_contour(&mut self) -> Result<(), FontError> {
        if let Some(start) = self.contour_start.take() {
            // FreeType's CFF builder (`src/psaux/psobjs.c:1999-2047`)
            // removes explicit final on-curve points that duplicate the
            // contour start, then drops contours left with only one point.
            // In this decoder, both `contour_start` assignment sites
            // immediately push the start point, so `points.len() > start`.
            if self.points.len() > start + 1 {
                let first = &self.points[start];
                let last = self.points[self.points.len() - 1];
                // Supported Type2 curve operators append their on-curve
                // endpoint atomically, so an off-curve final point is only a
                // defensive state for future operators or partial failures.
                if last.on_curve && first.x == last.x && first.y == last.y {
                    self.points.pop();
                }
            }

            if self.points.len() == start + 1 {
                self.points.pop();
            } else {
                let end = u16::try_from(self.points.len() - 1)
                    .map_err(|_| FontError::InvalidOutline("CFF: too many points".into()))?;
                self.end_pts.push(end);
            }
        }
        Ok(())
    }

    fn line_to(&mut self, dx: i32, dy: i32) {
        self.ensure_contour_start();
        self.x += dx;
        self.y += dy;
        self.points.push(OutlinePoint {
            x: self.x,
            y: self.y,
            on_curve: true,
            tag: TYPE2_TAG_ON,
        });
    }

    fn curve_to(&mut self, dx1: i32, dy1: i32, dx2: i32, dy2: i32, dx3: i32, dy3: i32) {
        self.ensure_contour_start();
        let c1x = self.x + dx1;
        let c1y = self.y + dy1;
        let c2x = c1x + dx2;
        let c2y = c1y + dy2;
        self.x = c2x + dx3;
        self.y = c2y + dy3;
        self.points.push(OutlinePoint {
            x: c1x,
            y: c1y,
            on_curve: false,
            tag: TYPE2_TAG_CUBIC,
        });
        self.points.push(OutlinePoint {
            x: c2x,
            y: c2y,
            on_curve: false,
            tag: TYPE2_TAG_CUBIC,
        });
        self.points.push(OutlinePoint {
            x: self.x,
            y: self.y,
            on_curve: true,
            tag: TYPE2_TAG_ON,
        });
    }

    fn ensure_contour_start(&mut self) {
        if self.contour_start.is_none() {
            // FreeType's Type2 decoder starts drawing from the current point
            // if a path operator appears before an explicit moveto.
            self.contour_start = Some(self.points.len());
            self.points.push(OutlinePoint {
                x: self.x,
                y: self.y,
                on_curve: true,
                tag: TYPE2_TAG_ON,
            });
        }
    }

    fn hmoveto(&mut self) -> Result<(), FontError> {
        self.take_width_for(1);
        if self.stack.len() != 1 {
            return Err(FontError::InvalidOutline(
                "CFF: hmoveto argument count".into(),
            ));
        }
        self.move_to(self.stack[0], 0)
    }

    fn vmoveto(&mut self) -> Result<(), FontError> {
        self.take_width_for(1);
        if self.stack.len() != 1 {
            return Err(FontError::InvalidOutline(
                "CFF: vmoveto argument count".into(),
            ));
        }
        self.move_to(0, self.stack[0])
    }

    fn rmoveto(&mut self) -> Result<(), FontError> {
        self.take_width_for(2);
        if self.stack.len() != 2 {
            return Err(FontError::InvalidOutline(
                "CFF: rmoveto argument count".into(),
            ));
        }
        self.move_to(self.stack[0], self.stack[1])
    }

    fn rlineto(&mut self) -> Result<(), FontError> {
        if !self.width_seen && self.stack.len() % 2 == 1 {
            // FreeType's Type2 path (`src/psaux/psintrp.c`) limits optional
            // width parsing to stems, moveto, and endchar; `rlineto` consumes
            // dx/dy pairs directly and rejects an odd stack.
            return Err(FontError::InvalidOutline(
                "CFF: rlineto argument count".into(),
            ));
        }
        if self.stack.is_empty() || !self.stack.len().is_multiple_of(2) {
            return Err(FontError::InvalidOutline(
                "CFF: rlineto argument count".into(),
            ));
        }
        let values = self.stack.clone();
        for pair in values.chunks_exact(2) {
            self.line_to(pair[0], pair[1]);
        }
        Ok(())
    }

    fn hv_line(&mut self, horizontal_first: bool) -> Result<(), FontError> {
        if self.stack.is_empty() {
            return Err(FontError::InvalidOutline(
                "CFF: hlineto/vlineto missing args".into(),
            ));
        }
        let mut horizontal = horizontal_first;
        let values = self.stack.clone();
        for value in values {
            if horizontal {
                self.line_to(value, 0);
            } else {
                self.line_to(0, value);
            }
            horizontal = !horizontal;
        }
        self.width_seen = true;
        Ok(())
    }

    fn rrcurveto(&mut self) -> Result<(), FontError> {
        if !self.width_seen && self.stack.len() % 6 == 1 {
            // FreeType's Type2 path (`src/psaux/psintrp.c`) does not consume
            // an optional width for `rrcurveto`; it requires complete
            // six-operand curve tuples.
            return Err(FontError::InvalidOutline(
                "CFF: rrcurveto argument count".into(),
            ));
        }
        if self.stack.is_empty() || !self.stack.len().is_multiple_of(6) {
            return Err(FontError::InvalidOutline(
                "CFF: rrcurveto argument count".into(),
            ));
        }
        let values = self.stack.clone();
        for args in values.chunks_exact(6) {
            self.curve_to(args[0], args[1], args[2], args[3], args[4], args[5]);
        }
        Ok(())
    }

    fn hvcurveto(&mut self) -> Result<(), FontError> {
        self.alternating_curve(true)
    }

    fn vhcurveto(&mut self) -> Result<(), FontError> {
        self.alternating_curve(false)
    }

    fn alternating_curve(&mut self, horizontal_first: bool) -> Result<(), FontError> {
        // FreeType treats five operands here as the optional final delta, not
        // as an initial width (`src/psaux/t2decode.c`).
        if self.stack.len() < 4 {
            return Err(FontError::InvalidOutline(
                "CFF: hvcurveto/vhcurveto argument count".into(),
            ));
        }
        let mut values = self.stack.clone();
        let mut horizontal = horizontal_first;
        while values.len() >= 4 {
            let last_delta = values.len() == 5;
            if horizontal {
                let dx1 = values.remove(0);
                let dx2 = values.remove(0);
                let dy2 = values.remove(0);
                let dy3 = values.remove(0);
                let dx3 = if last_delta { values.remove(0) } else { 0 };
                self.curve_to(dx1, 0, dx2, dy2, dx3, dy3);
            } else {
                let dy1 = values.remove(0);
                let dx2 = values.remove(0);
                let dy2 = values.remove(0);
                let dx3 = values.remove(0);
                let dy3 = if last_delta { values.remove(0) } else { 0 };
                self.curve_to(0, dy1, dx2, dy2, dx3, dy3);
            }
            horizontal = !horizontal;
        }
        if !values.is_empty() {
            return Err(FontError::InvalidOutline(
                "CFF: hvcurveto/vhcurveto trailing args".into(),
            ));
        }
        Ok(())
    }
}

fn read_type2_number(data: &[u8], pos: usize) -> Result<(i32, usize), FontError> {
    let byte = *data
        .get(pos)
        .ok_or_else(|| FontError::InvalidOutline("CFF: Type2 number overflow".into()))?;
    match byte {
        28 => {
            let bytes = data
                .get(pos + 1..pos + 3)
                .ok_or_else(|| FontError::InvalidOutline("CFF: Type2 shortint overflow".into()))?;
            Ok((i32::from(i16::from_be_bytes([bytes[0], bytes[1]])), pos + 3))
        }
        32..=246 => Ok((i32::from(byte) - 139, pos + 1)),
        247..=250 => {
            let next = i32::from(*data.get(pos + 1).ok_or_else(|| {
                FontError::InvalidOutline("CFF: Type2 positive number overflow".into())
            })?);
            Ok((((i32::from(byte) - 247) * 256) + next + 108, pos + 2))
        }
        251..=254 => {
            let next = i32::from(*data.get(pos + 1).ok_or_else(|| {
                FontError::InvalidOutline("CFF: Type2 negative number overflow".into())
            })?);
            Ok((-((i32::from(byte) - 251) * 256) - next - 108, pos + 2))
        }
        255 => {
            let bytes = data
                .get(pos + 1..pos + 5)
                .ok_or_else(|| FontError::InvalidOutline("CFF: Type2 fixed overflow".into()))?;
            Ok((
                i32::from_be_bytes([bytes[0], bytes[1], bytes[2], bytes[3]]) >> 16,
                pos + 5,
            ))
        }
        _ => Err(FontError::InvalidOutline(
            "CFF: invalid Type2 number".into(),
        )),
    }
}
