[workspace]

[package]
name = "ffi-bench"
version = "0.1.0"
edition = "2024"
rust-version = "1.87"

[[bin]]
name = "ffi-bench"
path = "src/main.rs"

[[bin]]
name = "profiler"
path = "src/profiler.rs"

[dependencies]
fontdone = { path = ".." }
fontdone-ffi-c = { path = "../ffi-c" }

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
