[package]
name = "pillow-rs"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Pure Rust image processing — Pillow reimplementation"

[lib]
name = "pillow_rs"

[dependencies]
pillow-rs-image = { path = "../pillow-rs-image" }
log = "0.4"
png = "0.18"
thiserror = "1"
csscolorparser = "0.8"
fontdue = "0.9"
wgpu = "24"
pollster = "0.3"
bytemuck = { version = "1", features = ["derive"] }


[lints]
workspace = true
