#!/usr/bin/env python3
"""Generate PIL coverage fixture using actual Python Pillow 12.2.0.

Runs Pillow against the fonts in fonts_autohint/, captures getmask SHA-256
and getbbox values for each font × size × codepoint. Writes the output
in the same format as the original coverage_matrix.json generated by PIL.

Usage: python3 scripts/build_pil_fixture.py
Output: pillow-rs-freetype/tests/fixtures/coverage_matrix.json
"""

import os, sys, json, hashlib

try:
    from PIL import ImageFont
except ImportError:
    print("ERROR: Pillow not installed. pip install Pillow", file=sys.stderr)
    sys.exit(1)

FONT_DIR = 'pillow-rs-freetype/tests/fixtures/input/fonts_autohint'
SIZES = [10, 12, 16, 20, 24]
CODEPOINTS = list(range(33, 127))  # printable ASCII

# Same 8 Latin fonts as the FT Latin matrix (font-reduction-research.md)
# Both PIL and FreeType tests use identical font files.
FONT_MAP = {
    'DejaVuSans-ExtraLight':     'DejaVuSans-ExtraLight.ttf',
    'DejaVuSans-Oblique':        'DejaVuSans-Oblique.ttf',
    'DejaVuSansMono':            'DejaVuSansMono.ttf',
    'DejaVuSerif-Bold':          'DejaVuSerif-Bold.ttf',
    'DejaVuSerif-Italic':        'DejaVuSerif-Italic.ttf',
    'LiberationSans-Regular':    'LiberationSans-Regular.ttf',
    'LiberationSansNarrow-Bold': 'LiberationSansNarrow-Bold.ttf',
    'NotoSans-Bold':             'NotoSans-Bold.ttf',
}

def main():
    rows = []

    for pil_name, filename in FONT_MAP.items():
        font_path = os.path.join(FONT_DIR, filename)
        if not os.path.exists(font_path):
            print(f"SKIP {pil_name}: {filename} not found", file=sys.stderr)
            continue

        for size in SIZES:
            font = ImageFont.FreeTypeFont(font_path, size)

            # Metrics
            try:
                asc, desc = font.getmetrics()
                rows.append({"id": f"{pil_name}_{size}_getmetrics", "font": pil_name,
                    "size_pt": size, "codepoint": 0, "char": "", "operation": "getmetrics",
                    "status": "active", "ref_value": [asc, desc]})
            except: pass

            # Name
            try:
                family, style = font.getname()
                rows.append({"id": f"{pil_name}_{size}_getname", "font": pil_name,
                    "size_pt": size, "codepoint": 0, "char": "", "operation": "getname",
                    "status": "active", "ref_value": [family, style]})
            except: pass

            # Length
            try:
                length = font.getlength("Hello")
                rows.append({"id": f"{pil_name}_{size}_getlength_hello", "font": pil_name,
                    "size_pt": size, "codepoint": 0, "char": "Hello", "operation": "getlength",
                    "status": "active", "ref_value": length})
            except: pass

            # Per-character getmask and getbbox
            for cp in CODEPOINTS:
                ch = chr(cp)
                try:
                    mask = font.getmask(ch)
                    if mask:
                        pixels = bytes(mask) if hasattr(mask, 'tobytes') else bytes(mask)
                        sha = hashlib.sha256(pixels).hexdigest()
                        rows.append({"id": f"{pil_name}_{size}_{cp}_getmask", "font": pil_name,
                            "size_pt": size, "codepoint": cp, "char": ch,
                            "operation": "getmask", "status": "active",
                            "ref_sha256": sha, "ref_size": list(mask.size)})
                except: pass

                try:
                    bbox = font.getbbox(ch)
                    if bbox:
                        rows.append({"id": f"{pil_name}_{size}_{cp}_getbbox", "font": pil_name,
                            "size_pt": size, "codepoint": cp, "char": ch,
                            "operation": "getbbox", "status": "active",
                            "ref_value": list(bbox)})
                except: pass

        count = sum(1 for r in rows if r['font'] == pil_name)
        print(f"  {pil_name}: {count} rows", file=sys.stderr)

    output = {
        "version": "2.0.0",
        "generator": "Pillow 12.2.0 (Python PIL via scripts/build_pil_fixture.py)",
        "font_source": "fonts_autohint",
        "hinting": "autohint",
        "mode": "PIL",
        "rows": rows,
        "summary": {
            "total_rows": len(rows),
            "active_rows": len(rows),
            "fonts": len(FONT_MAP),
            "sizes": len(SIZES),
            "glyphs": len(CODEPOINTS),
        }
    }

    path = 'pillow-rs-freetype/tests/fixtures/coverage_matrix.json'
    with open(path, 'w') as f:
        json.dump(output, f, indent=2)
    print(f"\nDone: {len(rows)} rows → {path}", file=sys.stderr)

if __name__ == '__main__':
    main()
