#!/usr/bin/env python3
"""Extract blue string entries from FreeType's afblue.dat and generate Rust code.

Usage: python3 scripts/extract_blues.py \
    pillow-rs-freetype/freetype/src/autofit/afblue.dat \
    > pillow-rs-freetype/src/autohint/blue_strings.rs

The output is a Rust module with:
- A `BlueScript` enum (Latin, Greek, Cyrillic, etc.)
- `SCRIPT_TO_ENTRIES: &[(BlueScript, &[BlueEntry])]`
- `BlueEntry` struct with chars, props, script tag
"""

import re
import sys

def parse_afblue(data):
    """Parse afblue.dat into a list of sections with their string arrays."""
    sections = []
    current_section = None
    current_records = {}  # name -> list of strings
    
    lines = data.split('\n')
    section_pattern = re.compile(r'^\s*AF_BLUE_STRING_(\w+)\s+(\w+)\s+(\w+)\s*:')
    record_pattern = re.compile(r'^\s*AF_BLUE_STRING_(\w+)\s*$')
    
    for line in lines:
        # Check for section header
        m = section_pattern.match(line)
        if m:
            if current_section and current_records:
                sections.append((current_section, dict(current_records)))
            current_section = m.group(1)
            current_records = {}
            continue
        
        # Check for record name
        m = record_pattern.match(line)
        if m:
            current_name = m.group(1)
            current_records[current_name] = []
            continue
        
        # Check for string data (quoted)
        line = line.strip()
        if line.startswith('"') and line.endswith('"'):
            s = line[1:-1]
            if s and current_name in current_records:
                # Split by spaces to get individual characters/clusters
                chars = s.split()
                current_records[current_name].extend(chars)
    
    if current_section and current_records:
        sections.append((current_section, dict(current_records)))
    
    return sections

def codepoint_to_rust(ch):
    """Convert a UTF-8 character or cluster to Rust char literals."""
    if len(ch) == 1:
        cp = ord(ch)
        if cp < 128 and ch.isprintable() and ch not in ("'", "\\"):
            return f"'{ch}'"
        else:
            return f"'\\u{{{cp:04X}}}'"
    else:
        # Multi-byte cluster - store as char array
        cps = [f"'\\u{{{ord(c):04X}}}'" for c in ch]
        return f"[{', '.join(cps)}]"

def script_to_props(script_name, base_name):
    """Map afblue.dat section names to AF_BLUE_PROP_* flags."""
    name = base_name.upper()
    props = []
    
    # These are derived from afblue.h / aflatin.h flag constants
    if 'TOP' in name and 'BOTTOM' not in name:
        props.append('AF_BLUE_PROP_LATIN_TOP')
    if 'BOTTOM' in name and 'TOP' not in name.replace('BOTTOM', ''):
        props.append('AF_BLUE_PROP_LATIN_BOTTOM')
    if 'X_HEIGHT' in name or 'SMALL_TOP' in name:
        props.append('AF_BLUE_PROP_LATIN_X_HEIGHT')
    if 'SUBS' in script_name:
        props.append('AF_BLUE_PROP_LATIN_NEUTRAL')
    if 'SMALL' in name or 'SUBS' in name:
        pass  # handled above
    
    if not props:
        props.append('0')
    
    return ' | '.join(props)

def main():
    if len(sys.argv) < 2:
        print("Usage: extract_blues.py <afblue.dat>", file=sys.stderr)
        sys.exit(1)
    
    with open(sys.argv[1]) as f:
        data = f.read()
    
    sections = parse_afblue(data)
    
    print("//! Auto-generated blue string table extracted from FreeType's afblue.dat.")
    print("//! Generated by scripts/extract_blues.py")
    print("//! DO NOT EDIT BY HAND")
    print()
    print("use super::types::*;")
    print()
    
    # Collect all unique character strings per entry
    print("/// One blue string entry: characters + property flags.")
    print("#[derive(Debug, Clone)]")
    print("pub struct BlueStringEntry {")
    print("    pub chars: &'static [char],")
    print("    pub props: u32,")
    print("}")
    print()
    
    # We'll generate a struct per script section
    all_entries = {}
    
    for script_name, records in sections:
        entry_list = []
        for base_name, chars in sorted(records.items()):
            rust_chars = ', '.join(codepoint_to_rust(c) for c in chars)
            props = '0'  # simplified for now
            
            # Determine properties from the name
            for suffix, prop_name in [
                ('CAPITAL_TOP', 'AF_BLUE_PROP_LATIN_TOP'),
                ('CAPITAL_BOTTOM', 'AF_BLUE_PROP_LATIN_CAPITAL_BOTTOM'),
                ('SMALL_F_TOP', 'AF_BLUE_PROP_LATIN_TOP'),
                ('SMALL_TOP', 'AF_BLUE_PROP_LATIN_TOP | AF_BLUE_PROP_LATIN_X_HEIGHT'),
                ('SMALL_BOTTOM', 'AF_BLUE_PROP_LATIN_SMALL_BOTTOM'),
                ('SMALL_DESCENDER', '0'),
                ('SUBS_CAPITAL_TOP', 'AF_BLUE_PROP_LATIN_TOP'),
                ('SUBS_CAPITAL_BOTTOM', 'AF_BLUE_PROP_LATIN_CAPITAL_BOTTOM'),
                ('SUBS_SMALL_F_TOP', 'AF_BLUE_PROP_LATIN_TOP'),
                ('SUBS_SMALL', 'AF_BLUE_PROP_LATIN_TOP | AF_BLUE_PROP_LATIN_X_HEIGHT'),
                ('SUBS_SMALL_BOTTOM', 'AF_BLUE_PROP_LATIN_SMALL_BOTTOM'),
                ('SUBS_SMALL_DESCENDER', '0'),
            ]:
                if base_name == suffix:
                    props = prop_name
                    break
            
            entry_list.append((base_name, rust_chars, props, chars))
        
        all_entries[script_name] = entry_list
    
    # Output the entries for all scripts
    for script_name, entry_list in sorted(all_entries.items()):
        for base_name, rust_chars, props, original_chars in entry_list:
            print(f"/// Blue string: {script_name}.{base_name} ({' '.join(original_chars)})")
            print(f"pub const {script_name}_{base_name}: BlueStringEntry = BlueStringEntry {{")
            print(f"    chars: &[{rust_chars}],")
            print(f"    props: {props},")
            print(f"}};")
            print()
    
    # Output a lookup table: script name -> list of entries
    print("/// All blue string entries grouped by script.")
    print("pub const ALL_BLUE_ENTRIES: &[(&[BlueStringEntry])] = &[")
    
    for script_name, entry_list in sorted(all_entries.items()):
        names = ', '.join(f"&{script_name}_{base_name}" for base_name, _, _, _ in entry_list)
        print(f"    &[{names}],")
    
    print("];")

if __name__ == '__main__':
    main()
