#!/usr/bin/env python3
"""Generate public FreeType constant tables for unified parity tests."""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
import tempfile
from pathlib import Path

import audit_api_abi


ROOT = Path(__file__).resolve().parents[1]
INCLUDE_ROOT = ROOT / "freetype" / "include"

EXCLUDED_SYMBOLS = {
    "FT_DEPRECATED_ATTRIBUTE",
    "FT_ERROR_END_LIST",
    "FT_ERROR_START_LIST",
    "FT_ERR_BASE",
    "FT_ERR_PREFIX",
    "FT_ERR_PROTOS_DEFINED",
    "FT_INCLUDE_ERR_PROTOS",
    "FT_MODERR_END_LIST",
    "FT_MODERR_START_LIST",
    "FT_NEED_EXTERN_C",
}

EXCLUDED_SYMBOL_HEADERS = {
    "freetype/ftmac.h",
}

EXCLUDED_INCLUDE_HEADERS = {
    "freetype/fterrdef.h",
    "freetype/ftmac.h",
    "freetype/ftmoderr.h",
}


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--oracle-inc", type=Path)
    parser.add_argument("--rust-src", type=Path)
    parser.add_argument("--test-lookup", type=Path)
    args = parser.parse_args()

    symbols, headers = public_integer_symbols()

    if args.oracle_inc:
        write_oracle_include(ROOT / args.oracle_inc, symbols, headers)

    if args.rust_src or args.test_lookup:
        values = evaluate_c_constants(symbols, headers)
        existing = existing_rust_constants(ROOT / "src" / "ffi" / "constants.rs")
        if args.rust_src:
            write_rust_constants(ROOT / args.rust_src, values, existing)
        if args.test_lookup:
            write_test_lookup(ROOT / args.test_lookup, values)


def public_integer_symbols() -> tuple[list[str], list[str]]:
    inventory = audit_api_abi.parse_c_headers(INCLUDE_ROOT)
    symbols: set[str] = set()
    headers: set[str] = set()

    for name, meta in inventory["macros"].items():
        if should_skip_symbol(name, meta["value"], meta["file"]):
            continue
        symbols.add(name)
        headers.add(meta["file"])

    for bucket in ("enum_variants", "error_codes"):
        for name, meta in inventory[bucket].items():
            if should_skip_symbol(name, None, meta["file"]):
                continue
            symbols.add(name)
            headers.add(meta["file"])

    return sorted(symbols), sorted(header for header in headers if header not in EXCLUDED_INCLUDE_HEADERS)


def should_skip_symbol(name: str, value: str | None, header: str) -> bool:
    if header in EXCLUDED_SYMBOL_HEADERS or name in EXCLUDED_SYMBOLS or name.endswith("_Func"):
        return True
    if value and is_function_like_macro(value):
        return True
    return value == ""


def is_function_like_macro(value: str) -> bool:
    return bool(
        re.match(
            r"^\s*\(\s*[A-Za-z_][A-Za-z0-9_]*(?:\s*,\s*[A-Za-z_][A-Za-z0-9_]*)*\s*\)\s+",
            value,
        )
    )


def include_lines(headers: list[str]) -> list[str]:
    lines = ["#include <ft2build.h>", "#include FT_FREETYPE_H"]
    lines.extend(
        f"#include <{header}>"
        for header in headers
        if header != "freetype/freetype.h"
    )
    return lines


def write_oracle_include(path: Path, symbols: list[str], headers: list[str]) -> None:
    lines = [
        "/* @generated by scripts/generate_public_constants.py; do not edit. */",
        *include_lines(headers),
        "",
        "static int emit_generated_constant_value(const char* symbol, long long* value) {",
        "#define CONST_VALUE(name) \\",
        "    if (streq(symbol, #name)) { \\",
        "        *value = (long long)(name); \\",
        "        return 1; \\",
        "    } else",
    ]
    lines.extend(f"    CONST_VALUE({symbol})" for symbol in symbols)
    lines.extend(
        [
            "    {",
            "        return 0;",
            "    }",
            "#undef CONST_VALUE",
            "}",
            "",
        ]
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines))


def evaluate_c_constants(symbols: list[str], headers: list[str]) -> dict[str, int]:
    source = [
        *include_lines(headers),
        "#include <stdio.h>",
        "int main(void) {",
    ]
    source.extend(f'    printf("{symbol}\\t%lld\\n", (long long)({symbol}));' for symbol in symbols)
    source.append("    return 0;")
    source.append("}")

    with tempfile.TemporaryDirectory() as tmp:
        tmp_path = Path(tmp)
        c_path = tmp_path / "constants.c"
        out_path = tmp_path / "constants"
        c_path.write_text("\n".join(source))
        subprocess.run(
            [
                "cc",
                "-std=c11",
                "-I",
                str(INCLUDE_ROOT),
                str(c_path),
                "-o",
                str(out_path),
            ],
            cwd=ROOT,
            check=True,
        )
        output = subprocess.check_output([str(out_path)], text=True)

    values: dict[str, int] = {}
    for line in output.splitlines():
        name, value = line.split("\t", 1)
        values[name] = int(value)
    return values


def existing_rust_constants(path: Path) -> set[str]:
    if not path.exists():
        return set()
    return set(re.findall(r"pub\s+const\s+([A-Za-z_][A-Za-z0-9_]*)\s*:", path.read_text()))


def write_rust_constants(path: Path, values: dict[str, int], existing: set[str]) -> None:
    lines = [
        "// @generated by scripts/generate_public_constants.py; do not edit by hand.",
        "",
    ]
    for name, value in values.items():
        if name in existing:
            continue
        lines.append(f"pub const {name}: i64 = {value};")
    lines.append("")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines))


def write_test_lookup(path: Path, values: dict[str, int]) -> None:
    lines = [
        "#![allow(missing_docs)]",
        "",
        "// @generated by scripts/generate_public_constants.py; do not edit by hand.",
        "",
        "use fontdone::ffi::*;",
        "",
        "fn constant_to_i64<T>(value: T) -> Option<i64>",
        "where",
        "    T: TryInto<i64>,",
        "{",
        "    value.try_into().ok()",
        "}",
        "",
        "pub fn generated_rust_constant(symbol: &str) -> Option<i64> {",
        "    match symbol {",
    ]
    for name in values:
        lines.extend(
            [
                f'        "{name}" => {{',
                f"            constant_to_i64({name})",
                "        },",
            ]
        )
    lines.extend(
        [
            "        _ => None,",
            "    }",
            "}",
            "",
        ]
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines))


if __name__ == "__main__":
    sys.exit(main())
