#!/usr/bin/env python3
"""Group pending public parity routes by repeated operation/input shape.

The route audit intentionally keeps many rows pending until the same concrete
input is exercised against pinned C FreeType, Rust FFI, C ABI, and WASM ABI.
This report does not promote rows.  It identifies the largest mechanically
related pending batches so parity work starts from shared input contracts rather
than subjective family labels.
"""

from __future__ import annotations

import argparse
import collections
import hashlib
import json
from pathlib import Path
from typing import Any


def stable_projection(value: Any) -> Any:
    """Return a deterministic subset suitable for operation/input hashing."""
    if isinstance(value, dict):
        return {key: stable_projection(value[key]) for key in sorted(value)}
    if isinstance(value, list):
        return [stable_projection(item) for item in value]
    return value


def row_hash(row: dict[str, Any]) -> str:
    key = {
        "operation": row.get("operation"),
        "assets": row.get("assets"),
        "params": row.get("params"),
        "expect_error": row.get("expect_error"),
        "allow_oracle_errors": row.get("allow_oracle_errors"),
        "compare_error_output": row.get("compare_error_output"),
    }
    payload = json.dumps(stable_projection(key), sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()[:12]


def load_pending_rows(path: Path) -> list[dict[str, Any]]:
    data = json.loads(path.read_text())
    return [row for row in data["rows"] if row.get("category") == "pending-route"]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--route-audit-json",
        default="target/api-abi-audit/route_audit.json",
        type=Path,
        help="route audit JSON generated by make route-audit",
    )
    parser.add_argument(
        "--limit",
        default=40,
        type=int,
        help="maximum number of duplicate buckets to print",
    )
    args = parser.parse_args()

    pending = load_pending_rows(args.route_audit_json)
    buckets: dict[tuple[str, str], list[dict[str, Any]]] = collections.defaultdict(list)
    for row in pending:
        buckets[(row.get("operation", ""), row_hash(row))].append(row)

    duplicate_buckets = [
        (operation, digest, rows)
        for (operation, digest), rows in buckets.items()
        if len(rows) > 1
    ]
    duplicate_buckets.sort(key=lambda item: (-len(item[2]), item[0], item[1]))

    print(f"pending_route_rows={len(pending)}")
    print(f"duplicate_operation_input_buckets={len(duplicate_buckets)}")
    print()
    for operation, digest, rows in duplicate_buckets[: args.limit]:
        families = collections.Counter(row["case_id"].split(".", 1)[0] for row in rows)
        print(
            f"{len(rows):>3}  operation={operation}  input_hash={digest}  "
            f"families={dict(families)}"
        )
        for row in rows:
            variant = f"  variant={row.get('variant_id')}" if row.get("variant_id") else ""
            print(f"     - {row['case_id']}{variant}")
        print()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
