#!/usr/bin/env python3
"""One-shot migration: convert old fixtures/ JSONs → new input/jsons/ format.

Old format (per op+mode):  { operation: {type, module, target, params}, input: {mode, size, bytes}, expected: {result_type, value} }
New format (per op, array): { operation: {module, target}, cases: [{id, mode, input, params}] }

Only creates input JSONs — outputs are regenerated by scripts/generate_fixtures.py.
"""

import json
from pathlib import Path
from collections import defaultdict

ROOT = Path(__file__).parent.parent
OLD_DIR = ROOT / "tests" / "fixtures"
NEW_DIR = ROOT / "tests" / "fixtures" / "input" / "jsons"
NEW_DIR.mkdir(parents=True, exist_ok=True)

# Group old fixtures by operation
groups = defaultdict(list)
for fpath in sorted(OLD_DIR.glob("*.json")):
    try:
        fx = json.loads(fpath.read_text())
    except Exception:
        continue
    if "operation" not in fx:
        continue
    op = fx["operation"]
    op_key = f"{op.get('module', '?')}.{op['target']}"
    groups[op_key].append((fpath, fx))

for op_key, items in sorted(groups.items()):
    module, target = op_key.split(".", 1)
    cases = []
    for fpath, fx in items:
        inp = fx.get("input", {})
        mode = inp.get("mode", "L")
        params = fx["operation"].get("params", {})

        # Strip sentinel values — the new engine passes params directly
        clean_params = {}
        for k, v in params.items():
            if isinstance(v, str) and v.startswith("__"):
                continue  # Skip __CONVERT_TO__, __IDENTITY_LUT__, etc.
            clean_params[k] = v

        # Use the old fixture filename component as part of case id
        case_id = fpath.stem  # e.g. "Image_resize_L"

        cases.append({
            "id": case_id,
            "mode": mode,
            "input": {"source": "reference_rgb", "size": [256, 256]},
            "params": clean_params,
        })

    out_path = NEW_DIR / f"{op_key.replace('.', '_')}.json"
    spec = {
        "format_version": 2,
        "operation": {"module": module, "target": target},
        "cases": cases,
    }
    out_path.write_text(json.dumps(spec, indent=2))
    print(f"  {out_path.stem}: {len(cases)} cases")

print(f"\nMigrated {len(groups)} operations to {NEW_DIR}")
