[build-system]
requires = ["maturin==1.14.1"]
build-backend = "maturin"

[project]
name = "pillow-rs"
version = "0.1.0"
description = "Pillow drop-in replacement powered by Rust"
requires-python = ">=3.8"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: CMU License (MIT-CMU)",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Rust",
    "Topic :: Multimedia :: Graphics",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

readme = "../README.md"
license = { text = "MIT-CMU" }

[project.urls]
Homepage = "https://github.com/appunni-m/pillow-rs"
Repository = "https://github.com/appunni-m/pillow-rs"
Documentation = "https://github.com/appunni-m/pillow-rs#readme"

[project.optional-dependencies]
dev = [
    "coverage==7.10.7; python_version >= '3.10'",
    "pyyaml==6.0.3",
    "pillow==12.2.0; python_version >= '3.10'",
    "numpy==2.2.6; python_version >= '3.10'",
]

[tool.maturin]
python-source = "python"
python-packages = ["pillow_rs", "RSPIL"]
module-name = "pillow_rs._core"
features = ["pyo3/extension-module"]
